const defaultState = {
  countries: [{
    name: 'Afghanistan',
    flag: 'https://disease.sh/assets/img/flags/af.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Albania',
    flag: 'https://disease.sh/assets/img/flags/al.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Algeria',
    flag: 'https://disease.sh/assets/img/flags/dz.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Andorra',
    flag: 'https://disease.sh/assets/img/flags/ad.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Angola',
    flag: 'https://disease.sh/assets/img/flags/ao.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Anguilla',
    flag: 'https://disease.sh/assets/img/flags/ai.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Antigua and Barbuda',
    flag: 'https://disease.sh/assets/img/flags/ag.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Argentina',
    flag: 'https://disease.sh/assets/img/flags/ar.png',
    continent: 'South America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Armenia',
    flag: 'https://disease.sh/assets/img/flags/am.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Aruba',
    flag: 'https://disease.sh/assets/img/flags/aw.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Australia',
    flag: 'https://disease.sh/assets/img/flags/au.png',
    continent: 'Australia-Oceania',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Austria',
    flag: 'https://disease.sh/assets/img/flags/at.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Azerbaijan',
    flag: 'https://disease.sh/assets/img/flags/az.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Bahamas',
    flag: 'https://disease.sh/assets/img/flags/bs.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Bahrain',
    flag: 'https://disease.sh/assets/img/flags/bh.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Bangladesh',
    flag: 'https://disease.sh/assets/img/flags/bd.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Barbados',
    flag: 'https://disease.sh/assets/img/flags/bb.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Belarus',
    flag: 'https://disease.sh/assets/img/flags/by.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Belgium',
    flag: 'https://disease.sh/assets/img/flags/be.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Belize',
    flag: 'https://disease.sh/assets/img/flags/bz.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Benin',
    flag: 'https://disease.sh/assets/img/flags/bj.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Bermuda',
    flag: 'https://disease.sh/assets/img/flags/bm.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Bhutan',
    flag: 'https://disease.sh/assets/img/flags/bt.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Bolivia',
    flag: 'https://disease.sh/assets/img/flags/bo.png',
    continent: 'South America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Bosnia',
    flag: 'https://disease.sh/assets/img/flags/ba.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Botswana',
    flag: 'https://disease.sh/assets/img/flags/bw.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Brazil',
    flag: 'https://disease.sh/assets/img/flags/br.png',
    continent: 'South America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'British Virgin Islands',
    flag: 'https://disease.sh/assets/img/flags/vg.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Brunei',
    flag: 'https://disease.sh/assets/img/flags/bn.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Bulgaria',
    flag: 'https://disease.sh/assets/img/flags/bg.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Burkina Faso',
    flag: 'https://disease.sh/assets/img/flags/bf.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Burundi',
    flag: 'https://disease.sh/assets/img/flags/bi.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Cabo Verde',
    flag: 'https://disease.sh/assets/img/flags/cv.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Cambodia',
    flag: 'https://disease.sh/assets/img/flags/kh.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Cameroon',
    flag: 'https://disease.sh/assets/img/flags/cm.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Canada',
    flag: 'https://disease.sh/assets/img/flags/ca.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Caribbean Netherlands',
    flag: 'https://disease.sh/assets/img/flags/bq.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Cayman Islands',
    flag: 'https://disease.sh/assets/img/flags/ky.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Central African Republic',
    flag: 'https://disease.sh/assets/img/flags/cf.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Chad',
    flag: 'https://disease.sh/assets/img/flags/td.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Channel Islands',
    flag: 'https://disease.sh/assets/img/flags/je.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Chile',
    flag: 'https://disease.sh/assets/img/flags/cl.png',
    continent: 'South America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'China',
    flag: 'https://disease.sh/assets/img/flags/cn.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Colombia',
    flag: 'https://disease.sh/assets/img/flags/co.png',
    continent: 'South America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Comoros',
    flag: 'https://disease.sh/assets/img/flags/km.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Congo',
    flag: 'https://disease.sh/assets/img/flags/cg.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Cook Islands',
    flag: 'https://disease.sh/assets/img/flags/ck.png',
    continent: 'Australia-Oceania',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Costa Rica',
    flag: 'https://disease.sh/assets/img/flags/cr.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Croatia',
    flag: 'https://disease.sh/assets/img/flags/hr.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Cuba',
    flag: 'https://disease.sh/assets/img/flags/cu.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Curaçao',
    flag: 'https://disease.sh/assets/img/flags/cw.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Cyprus',
    flag: 'https://disease.sh/assets/img/flags/cy.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Czechia',
    flag: 'https://disease.sh/assets/img/flags/cz.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Côte d\'Ivoire',
    flag: 'https://disease.sh/assets/img/flags/ci.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'DRC',
    flag: 'https://disease.sh/assets/img/flags/cd.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Denmark',
    flag: 'https://disease.sh/assets/img/flags/dk.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Diamond Princess',
    flag: 'https://disease.sh/assets/img/flags/unknown.png',
    continent: '',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Djibouti',
    flag: 'https://disease.sh/assets/img/flags/dj.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Dominica',
    flag: 'https://disease.sh/assets/img/flags/dm.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Dominican Republic',
    flag: 'https://disease.sh/assets/img/flags/do.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Ecuador',
    flag: 'https://disease.sh/assets/img/flags/ec.png',
    continent: 'South America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Egypt',
    flag: 'https://disease.sh/assets/img/flags/eg.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'El Salvador',
    flag: 'https://disease.sh/assets/img/flags/sv.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Equatorial Guinea',
    flag: 'https://disease.sh/assets/img/flags/gq.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Eritrea',
    flag: 'https://disease.sh/assets/img/flags/er.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Estonia',
    flag: 'https://disease.sh/assets/img/flags/ee.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Ethiopia',
    flag: 'https://disease.sh/assets/img/flags/et.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Falkland Islands (Malvinas)',
    flag: 'https://disease.sh/assets/img/flags/fk.png',
    continent: 'South America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Faroe Islands',
    flag: 'https://disease.sh/assets/img/flags/fo.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Fiji',
    flag: 'https://disease.sh/assets/img/flags/fj.png',
    continent: 'Australia-Oceania',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Finland',
    flag: 'https://disease.sh/assets/img/flags/fi.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'France',
    flag: 'https://disease.sh/assets/img/flags/fr.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'French Guiana',
    flag: 'https://disease.sh/assets/img/flags/gf.png',
    continent: 'South America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'French Polynesia',
    flag: 'https://disease.sh/assets/img/flags/pf.png',
    continent: 'Australia-Oceania',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Gabon',
    flag: 'https://disease.sh/assets/img/flags/ga.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Gambia',
    flag: 'https://disease.sh/assets/img/flags/gm.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Georgia',
    flag: 'https://disease.sh/assets/img/flags/ge.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Germany',
    flag: 'https://disease.sh/assets/img/flags/de.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Ghana',
    flag: 'https://disease.sh/assets/img/flags/gh.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Gibraltar',
    flag: 'https://disease.sh/assets/img/flags/gi.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Greece',
    flag: 'https://disease.sh/assets/img/flags/gr.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Greenland',
    flag: 'https://disease.sh/assets/img/flags/gl.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Grenada',
    flag: 'https://disease.sh/assets/img/flags/gd.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Guadeloupe',
    flag: 'https://disease.sh/assets/img/flags/gp.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Guatemala',
    flag: 'https://disease.sh/assets/img/flags/gt.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Guinea',
    flag: 'https://disease.sh/assets/img/flags/gn.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Guinea-Bissau',
    flag: 'https://disease.sh/assets/img/flags/gw.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Guyana',
    flag: 'https://disease.sh/assets/img/flags/gy.png',
    continent: 'South America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Haiti',
    flag: 'https://disease.sh/assets/img/flags/ht.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Holy See (Vatican City State)',
    flag: 'https://disease.sh/assets/img/flags/va.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Honduras',
    flag: 'https://disease.sh/assets/img/flags/hn.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Hong Kong',
    flag: 'https://disease.sh/assets/img/flags/hk.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Hungary',
    flag: 'https://disease.sh/assets/img/flags/hu.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Iceland',
    flag: 'https://disease.sh/assets/img/flags/is.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'India',
    flag: 'https://disease.sh/assets/img/flags/in.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Indonesia',
    flag: 'https://disease.sh/assets/img/flags/id.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Iran',
    flag: 'https://disease.sh/assets/img/flags/ir.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Iraq',
    flag: 'https://disease.sh/assets/img/flags/iq.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Ireland',
    flag: 'https://disease.sh/assets/img/flags/ie.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Isle of Man',
    flag: 'https://disease.sh/assets/img/flags/im.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Israel',
    flag: 'https://disease.sh/assets/img/flags/il.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Italy',
    flag: 'https://disease.sh/assets/img/flags/it.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Jamaica',
    flag: 'https://disease.sh/assets/img/flags/jm.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Japan',
    flag: 'https://disease.sh/assets/img/flags/jp.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Jordan',
    flag: 'https://disease.sh/assets/img/flags/jo.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Kazakhstan',
    flag: 'https://disease.sh/assets/img/flags/kz.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Kenya',
    flag: 'https://disease.sh/assets/img/flags/ke.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Kiribati',
    flag: 'https://disease.sh/assets/img/flags/ki.png',
    continent: 'Australia-Oceania',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Kuwait',
    flag: 'https://disease.sh/assets/img/flags/kw.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Kyrgyzstan',
    flag: 'https://disease.sh/assets/img/flags/kg.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Lao People\'s Democratic Republic',
    flag: 'https://disease.sh/assets/img/flags/la.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Latvia',
    flag: 'https://disease.sh/assets/img/flags/lv.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Lebanon',
    flag: 'https://disease.sh/assets/img/flags/lb.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Lesotho',
    flag: 'https://disease.sh/assets/img/flags/ls.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Liberia',
    flag: 'https://disease.sh/assets/img/flags/lr.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Libyan Arab Jamahiriya',
    flag: 'https://disease.sh/assets/img/flags/ly.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Liechtenstein',
    flag: 'https://disease.sh/assets/img/flags/li.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Lithuania',
    flag: 'https://disease.sh/assets/img/flags/lt.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Luxembourg',
    flag: 'https://disease.sh/assets/img/flags/lu.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'MS Zaandam',
    flag: 'https://disease.sh/assets/img/flags/unknown.png',
    continent: '',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Macao',
    flag: 'https://disease.sh/assets/img/flags/mo.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Macedonia',
    flag: 'https://disease.sh/assets/img/flags/mk.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Madagascar',
    flag: 'https://disease.sh/assets/img/flags/mg.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Malawi',
    flag: 'https://disease.sh/assets/img/flags/mw.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Malaysia',
    flag: 'https://disease.sh/assets/img/flags/my.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Maldives',
    flag: 'https://disease.sh/assets/img/flags/mv.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Mali',
    flag: 'https://disease.sh/assets/img/flags/ml.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Malta',
    flag: 'https://disease.sh/assets/img/flags/mt.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Marshall Islands',
    flag: 'https://disease.sh/assets/img/flags/mh.png',
    continent: 'Australia-Oceania',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Martinique',
    flag: 'https://disease.sh/assets/img/flags/mq.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Mauritania',
    flag: 'https://disease.sh/assets/img/flags/mr.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Mauritius',
    flag: 'https://disease.sh/assets/img/flags/mu.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Mayotte',
    flag: 'https://disease.sh/assets/img/flags/yt.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Mexico',
    flag: 'https://disease.sh/assets/img/flags/mx.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Micronesia',
    flag: 'https://disease.sh/assets/img/flags/fm.png',
    continent: 'Australia-Oceania',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Moldova',
    flag: 'https://disease.sh/assets/img/flags/md.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Monaco',
    flag: 'https://disease.sh/assets/img/flags/mc.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Mongolia',
    flag: 'https://disease.sh/assets/img/flags/mn.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Montenegro',
    flag: 'https://disease.sh/assets/img/flags/me.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Montserrat',
    flag: 'https://disease.sh/assets/img/flags/ms.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Morocco',
    flag: 'https://disease.sh/assets/img/flags/ma.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Mozambique',
    flag: 'https://disease.sh/assets/img/flags/mz.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Myanmar',
    flag: 'https://disease.sh/assets/img/flags/mm.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Namibia',
    flag: 'https://disease.sh/assets/img/flags/na.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Nauru',
    flag: 'https://disease.sh/assets/img/flags/nr.png',
    continent: 'Australia-Oceania',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Nepal',
    flag: 'https://disease.sh/assets/img/flags/np.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Netherlands',
    flag: 'https://disease.sh/assets/img/flags/nl.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'New Caledonia',
    flag: 'https://disease.sh/assets/img/flags/nc.png',
    continent: 'Australia-Oceania',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'New Zealand',
    flag: 'https://disease.sh/assets/img/flags/nz.png',
    continent: 'Australia-Oceania',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Nicaragua',
    flag: 'https://disease.sh/assets/img/flags/ni.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Niger',
    flag: 'https://disease.sh/assets/img/flags/ne.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Nigeria',
    flag: 'https://disease.sh/assets/img/flags/ng.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Niue',
    flag: 'https://disease.sh/assets/img/flags/nu.png',
    continent: 'Australia-Oceania',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Norway',
    flag: 'https://disease.sh/assets/img/flags/no.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Oman',
    flag: 'https://disease.sh/assets/img/flags/om.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Pakistan',
    flag: 'https://disease.sh/assets/img/flags/pk.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Palau',
    flag: 'https://disease.sh/assets/img/flags/pw.png',
    continent: 'Australia-Oceania',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Palestine',
    flag: 'https://disease.sh/assets/img/flags/ps.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Panama',
    flag: 'https://disease.sh/assets/img/flags/pa.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Papua New Guinea',
    flag: 'https://disease.sh/assets/img/flags/pg.png',
    continent: 'Australia-Oceania',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Paraguay',
    flag: 'https://disease.sh/assets/img/flags/py.png',
    continent: 'South America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Peru',
    flag: 'https://disease.sh/assets/img/flags/pe.png',
    continent: 'South America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Philippines',
    flag: 'https://disease.sh/assets/img/flags/ph.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Poland',
    flag: 'https://disease.sh/assets/img/flags/pl.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Portugal',
    flag: 'https://disease.sh/assets/img/flags/pt.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Qatar',
    flag: 'https://disease.sh/assets/img/flags/qa.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Romania',
    flag: 'https://disease.sh/assets/img/flags/ro.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Russia',
    flag: 'https://disease.sh/assets/img/flags/ru.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Rwanda',
    flag: 'https://disease.sh/assets/img/flags/rw.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Réunion',
    flag: 'https://disease.sh/assets/img/flags/re.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'S. Korea',
    flag: 'https://disease.sh/assets/img/flags/kr.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Saint Helena',
    flag: 'https://disease.sh/assets/img/flags/sh.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Saint Kitts and Nevis',
    flag: 'https://disease.sh/assets/img/flags/kn.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Saint Lucia',
    flag: 'https://disease.sh/assets/img/flags/lc.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Saint Martin',
    flag: 'https://disease.sh/assets/img/flags/mf.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Saint Pierre Miquelon',
    flag: 'https://disease.sh/assets/img/flags/pm.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Saint Vincent and the Grenadines',
    flag: 'https://disease.sh/assets/img/flags/vc.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Samoa',
    flag: 'https://disease.sh/assets/img/flags/ws.png',
    continent: 'Australia-Oceania',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'San Marino',
    flag: 'https://disease.sh/assets/img/flags/sm.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Sao Tome and Principe',
    flag: 'https://disease.sh/assets/img/flags/st.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Saudi Arabia',
    flag: 'https://disease.sh/assets/img/flags/sa.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Senegal',
    flag: 'https://disease.sh/assets/img/flags/sn.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Serbia',
    flag: 'https://disease.sh/assets/img/flags/rs.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Seychelles',
    flag: 'https://disease.sh/assets/img/flags/sc.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Sierra Leone',
    flag: 'https://disease.sh/assets/img/flags/sl.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Singapore',
    flag: 'https://disease.sh/assets/img/flags/sg.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Sint Maarten',
    flag: 'https://disease.sh/assets/img/flags/sx.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Slovakia',
    flag: 'https://disease.sh/assets/img/flags/sk.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Slovenia',
    flag: 'https://disease.sh/assets/img/flags/si.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Solomon Islands',
    flag: 'https://disease.sh/assets/img/flags/sb.png',
    continent: 'Australia-Oceania',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Somalia',
    flag: 'https://disease.sh/assets/img/flags/so.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'South Africa',
    flag: 'https://disease.sh/assets/img/flags/za.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'South Sudan',
    flag: 'https://disease.sh/assets/img/flags/ss.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Spain',
    flag: 'https://disease.sh/assets/img/flags/es.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Sri Lanka',
    flag: 'https://disease.sh/assets/img/flags/lk.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'St. Barth',
    flag: 'https://disease.sh/assets/img/flags/bl.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Sudan',
    flag: 'https://disease.sh/assets/img/flags/sd.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Suriname',
    flag: 'https://disease.sh/assets/img/flags/sr.png',
    continent: 'South America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Swaziland',
    flag: 'https://disease.sh/assets/img/flags/sz.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Sweden',
    flag: 'https://disease.sh/assets/img/flags/se.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Switzerland',
    flag: 'https://disease.sh/assets/img/flags/ch.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Syrian Arab Republic',
    flag: 'https://disease.sh/assets/img/flags/sy.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Taiwan',
    flag: 'https://disease.sh/assets/img/flags/tw.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Tajikistan',
    flag: 'https://disease.sh/assets/img/flags/tj.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Tanzania',
    flag: 'https://disease.sh/assets/img/flags/tz.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Thailand',
    flag: 'https://disease.sh/assets/img/flags/th.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Timor-Leste',
    flag: 'https://disease.sh/assets/img/flags/tl.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Togo',
    flag: 'https://disease.sh/assets/img/flags/tg.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Tonga',
    flag: 'https://disease.sh/assets/img/flags/to.png',
    continent: 'Australia-Oceania',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Trinidad and Tobago',
    flag: 'https://disease.sh/assets/img/flags/tt.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Tunisia',
    flag: 'https://disease.sh/assets/img/flags/tn.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Turkey',
    flag: 'https://disease.sh/assets/img/flags/tr.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Turks and Caicos Islands',
    flag: 'https://disease.sh/assets/img/flags/tc.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'UAE',
    flag: 'https://disease.sh/assets/img/flags/ae.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'UK',
    flag: 'https://disease.sh/assets/img/flags/gb.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'USA',
    flag: 'https://disease.sh/assets/img/flags/us.png',
    continent: 'North America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Uganda',
    flag: 'https://disease.sh/assets/img/flags/ug.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Ukraine',
    flag: 'https://disease.sh/assets/img/flags/ua.png',
    continent: 'Europe',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Uruguay',
    flag: 'https://disease.sh/assets/img/flags/uy.png',
    continent: 'South America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Uzbekistan',
    flag: 'https://disease.sh/assets/img/flags/uz.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Vanuatu',
    flag: 'https://disease.sh/assets/img/flags/vu.png',
    continent: 'Australia-Oceania',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Venezuela',
    flag: 'https://disease.sh/assets/img/flags/ve.png',
    continent: 'South America',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Vietnam',
    flag: 'https://disease.sh/assets/img/flags/vn.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Wallis and Futuna',
    flag: 'https://disease.sh/assets/img/flags/wf.png',
    continent: 'Australia-Oceania',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Western Sahara',
    flag: 'https://disease.sh/assets/img/flags/eh.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Yemen',
    flag: 'https://disease.sh/assets/img/flags/ye.png',
    continent: 'Asia',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Zambia',
    flag: 'https://disease.sh/assets/img/flags/zm.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  },
  {
    name: 'Zimbabwe',
    flag: 'https://disease.sh/assets/img/flags/zw.png',
    continent: 'Africa',
    todayCases: 0,
    todayDeaths: 0,
  }],
};

export default defaultState;
